# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 05:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(default=datetime.datetime(2016, 7, 5, 5, 58, 7, 260000, tzinfo=utc), upload_to='upload/thumbnail', verbose_name='\u5c01\u9762'),
            preserve_default=False,
        ),
    ]
